In [3]:
import numpy as np
import sys

In [10]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [6]:
b = np.array([[1,2,3,4],[2,5,4,2]])
print(b)

[[1 2 3 4]
 [2 5 4 2]]


In [5]:
#Get dimension
a.ndim

1

In [6]:
b.ndim

2

In [10]:
#Get type of array
a.dtype

dtype('int16')

In [11]:
print(a)

[1 2 3]


In [12]:
a.itemsize
#gives us the total number of bytes divided by 8
# i.e. gives us the number of bytes for one item

2

In [5]:
# Gives you the amount of rows and coloums and since there ais only one dimension in this
#therefore ther is only one number as the output
a.shape

(3,)

In [7]:
#Since there are two dimensions in this variable therefore the are two numbers present
# that is no. of rows and coloumns
b.shape

(2, 4)

# Accesing/Changing specific elements, rows, coloums etc. 

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
#Get a specific element [r,c]
a[1,5]

13

In [14]:
#We can also use slicing in this method
a[1,2:5]

array([10, 11, 12])

In [15]:
# Get a specific coloumn
a[:,3]

array([ 4, 11])