In [1]:
import numpy as np
import sys

In [9]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3,4],[2,5,4,2]])
print(b)

[[1 2 3 4]
 [2 5 4 2]]


In [5]:
#Get dimension
a.ndim

1

In [6]:
b.ndim

2

In [10]:
#Get type of array
a.dtype

dtype('int16')

In [11]:
print(a)

[1 2 3]


In [12]:
a.itemsize
#gives us the total number of bytes divided by 8
# i.e. gives us the number of bytes for one item

2